### ISSUE TITLE
Reals doesn’t like scientific notation

### ISSUE THREAD

**Issue by kseistrup** [rubenvannieuwpoort/reals#12]
```pytb
$ python
Python 3.10.7 (main, Sep  6 2022, 21:22:27) [GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from reals import pi
>>> pi * 1e9
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "~/.local/lib/python3.10/site-packages/reals/_real.py", line 89, in __mul__
    raise TypeError()
TypeError
>>>
```
That would be reals v0.0.2, installed from PyPI.

**Comment by rubenvannieuwpoort** [comment]
Hi, thanks for reporting the issue. 1e9 is a floating point number, and reals can't be combined with floating point numbers. I suggest that you use the `10**9` notation, which returns an `int`, or that you use the `Real.from_float` method:
```
>>> from reals import pi, Real
>>> pi * Real.from_float(1e9)
<reals._real.Real object at 0x1049a1690 (approximate value: 3141592653.58979)>
```

The reason that reals can't be combined with floating point numbers is that floating point numbers may silently lose precision:
```
>>> int(1e23)
99999999999999991611392
```
So if you would do `pi * 1e23` you would get a wrong result. If you have a suggestion for more intuitive behavior please let me know.

I do think that there should be a clear error message, this will be fixed.

**Comment by kseistrup** [comment]
Ah yes, you are of course right. I didn't think of `1e9` as a float because it doesn't look floaty.

Thanks for your suggestions!

**Comment by rubenvannieuwpoort** [comment]
In v0.0.3 this throws a type error with a better description:
```
$ python
Python 3.10.6 (main, Aug 10 2022, 11:40:04) [GCC 11.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from reals import pi
>>> pi * 1e9
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ruben/Desktop/reals/reals/_real.py", line 103, in __mul__
    raise_typeerror(other)
  File "/home/ruben/Desktop/reals/reals/_real.py", line 282, in raise_typeerror
    raise TypeError('Mixing float with reals is not supported. Use Real.from_float if you want to convert '
TypeError: Mixing float with reals is not supported. Use Real.from_float if you want to convert a float to a real.
>>> 
```

**Comment by kseistrup** [comment]
Very useful — thanks! :pray:
